"""Add subscription_type to user table

Revision ID: 33b4a3348144
Revises: 
Create Date: 2025-08-07 16:20:10.672326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33b4a3348144'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversation_date'), table_name='care_logs')
    op.drop_index(op.f('idx_conversation_id'), table_name='care_logs')
    op.create_index(op.f('ix_care_logs_conversation_date'), 'care_logs', ['conversation_date'], unique=False)
    op.create_index(op.f('ix_care_logs_conversation_id'), 'care_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_care_logs_id'), 'care_logs', ['id'], unique=False)
    op.drop_column('diagnosis_logs', 'user_age')
    op.drop_column('diagnosis_logs', 'user_education')
    op.add_column('user', sa.Column('subscription_type', sa.String(length=20), nullable=True, server_default='standard'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_type')
    op.add_column('diagnosis_logs', sa.Column('user_education', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('diagnosis_logs', sa.Column('user_age', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_care_logs_id'), table_name='care_logs')
    op.drop_index(op.f('ix_care_logs_conversation_id'), table_name='care_logs')
    op.drop_index(op.f('ix_care_logs_conversation_date'), table_name='care_logs')
    op.create_index(op.f('idx_conversation_id'), 'care_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_conversation_date'), 'care_logs', ['conversation_date'], unique=False)
    # ### end Alembic commands ###
